name: rowmate
description: RowMate App
#flutter_blue: ^0.7.3
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  material_design_icons_flutter: 4.0.5755
  meta: ^1.2.3
  equatable: ^1.2.5
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  flutter_blue: ^0.8.0
  flutter_colorpicker: 0.3.4
  qrscan: ^0.3.2
  permission_handler: ^8.1.4+2
  syncfusion_flutter_charts: ^19.2.56
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "RowMate App"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
